version: '3.9'

services:
  app:
    build: .
    ports:
      - 8000:8080
    environment:
      WEBHOOK_KEY: abcdefg
      NODE_ENV: production
      PORT: 8080
  test:
    build:
      context: .
      dockerfile: test.Dockerfile
    depends_on:
      - app
    ports:
      - 8888:8888
    environment:
      SYNC_KEY: abcdefg
      NODE_ENV: production
      TEST_HOST: app
      PORT: 8080
